# Cloudflare Pages configuration
name = "propflow360-web-dev"
compatibility_date = "2024-12-22"
pages_build_output_dir = "build/client"

[vars]
API_BASE_URL = "https://propflow360-api-dev.samuel-1e5.workers.dev"
SESSION_SECRET = "propflow360-session-secret-change-in-production"
